version: '3.7'

services:
  postgres:
    image: postgres:11
    container_name: legacy-postgres
    environment:
      POSTGRES_DB: legacydb
      POSTGRES_USER: legacyuser
      POSTGRES_PASSWORD: legacypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legacy-network

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: legacy-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - legacy-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  legacy-network:
    driver: bridge